### ISSUE TITLE
cricle menu

### ISSUE THREAD

**Issue by suprajasri** [szugyi/Android-CircleMenu#1]
this code is not working properly if i include odd no icons like... if i include 7 icons the rotation and and placement of icons are not proper.

**Comment by szugyi** [comment]
@iabdullo Sorry but this has not yet been fixed. I will try to fix it this weekend.

**Comment by challengemyself** [comment]
i have a problem,does it support android 2.3?

**Comment by iabdullo** [comment]
hi,
No, i don't need support 2.3

**Comment by szugyi** [comment]
It should work well from android 2.2.

**Comment by szugyi** [comment]
@suprajasri @iabdullo I have pushed a new version in which the rotation of odd/more than 6 icons has been fixed. However glitches of rotating to the center may occur. Try using different circle:speed settings for the CircleLayout to avoid it. I will try to reimplement the rotation mechanism to use property animation instead of runnable to avoid it, and have a smoother rotation in general.

**Comment by firojmd2002** [comment]
i have the same problem, i include 8 icons

**Comment by Harikrishna1234** [comment]
facing 8 icons problem

**Comment by szugyi** [comment]
@firojmd2002 @Harikrishna1234 What is the problem? Is it when you tap on an item, next to the one which is currently selected, then it does not move, but looks like as if you tapped the one already chosen?

**Comment by Harikrishna1234** [comment]
The problem is the item which is in the second position is not firing OnRotationFinishedListener when selected.

**Comment by Harikrishna1234** [comment]
All the other Seven items are working as expected, but the problem is only with the second item in the circular layout, the only problem which i mentioned earlier.

**Comment by szugyi** [comment]
@Harikrishna1234 Thanks, I was able to reproduce the problem. I will try to fix it during the weekend.

**Comment by Harikrishna1234** [comment]
Thank u, i find the issue is with the angle while debugging.

**Comment by szugyi** [comment]
@Harikrishna1234 I have just pushed a brand new implementation for the rotation, using Property Animations. Unfortunately these are only available from Android 3.0 (api 11). The old implementation has not changed yet, but i will try to figure out how to fix that too. In the meantime if you want to support only 3.0 or above, definitely use the new CircleLayout instead of the old one.

**Comment by iabdullo** [comment]
Thank you @szugyi it works perfect

**Comment by Harikrishna1234** [comment]
Thank you @szugyi  its working well :)

**Comment by firojmd2002** [comment]
Thank you @szugyi it works perfect

**Comment by szugyi** [comment]
The lib is now using the NineOldAndroids lib, so now it can be used bug free even under Android 3.0. The old implementation using Runnables has been removed. Thank you for your patience.
