### ISSUE TITLE
How to make background of the circle layout which rotate along the icons

### ISSUE THREAD

**Issue by Kevinnad** [szugyi/Android-CircleMenu#37]
How to make background of the circle layout which rotate along the icons. I tried it with seprate rotationanimation but it is out synch.

**Comment by szugyi** [comment]
Do you want to rotate the background of the CircleLayout togethet with the icons? Right now it is not supported. You might be able to implement it by changing the animateTo method of the CircleLayout, and rotate the background together with the icons.

**Comment by Kevinnad** [comment]
I tried that, but the background image animation is out synch, not equal to icon animation

**Comment by szugyi** [comment]
Could you show me how you tried to animate the background?

**Comment by Kevinnad** [comment]
Here is the code I added to the animateTo method:
(The Background Image I used is: https://s17.postimg.org/egnmh3da7/sword.png. (So the icons should be synced between the dividers in the wheel while rotating) 

RotateAnimation rotate; 
  private void animateTo(float endDegree, long duration) {
        if (animator != null && animator.isRunning() || Math.abs(angle - endDegree) < 1) {
            return;
        }
       // Rotation animation part //
        rotate = new RotateAnimation(angle, endDegree+20, Animation.RELATIVE_TO_SELF, 0.5f,       
        Animation.RELATIVE_TO_SELF, 0.5f);
        rotate.setDuration(duration);
        rotate.setInterpolator(new DecelerateInterpolator());
        rotate.setFillAfter(true);

        animator = ObjectAnimator.ofFloat(CircleLayout.this, "angle", angle, endDegree);
        animator.setDuration(duration);
        animator.setInterpolator(new LinearInterpolator());
        animator.addListener(new Animator.AnimatorListener() {
.........
        animator.start();
        image.startAnimation(rotate); // image - ImageView

**Comment by szugyi** [comment]
Do you even need any Icons? Why don't you just use this image, with the icons "burned" on top of it, so you have only one image you have to rotate. The tutorial which gave the basis of this project does just that, you can find it here: https://code.tutsplus.com/tutorials/android-sdk-creating-a-rotating-dialer--mobile-8868

If you need the logic which "pulls" the icons to fixed positions, you might be able to get that functionality by adding invisible views to the CircleLayout. I guess the background is lagging behind because it is a big image asset, and redrawing a big image can be time consuming.
