### ISSUE TITLE
TranslateAnimation for the CircleImageView

### ISSUE THREAD

**Issue by AruLNadhaN** [szugyi/Android-CircleMenu#7]
I need to Apply Translate Animation for all the CircleImageView whenever a Circle layout is Called.
To do that, where should I call the Translate Animation method. So that the Animation method will be called Everytime my Activity starts.

**Comment by szugyi** [comment]
Sorry for the late response. 
You could extend the CircleLayout, and call the Translate Animation in the onLayout method, but i'm not sure if that will work well, because the CircleLayout will rearrange them immediaely i guess. You might need to prevent it using a flag, or implement the translate animation directly in the CircleLayout yourself.
